apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentgateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
    - port: {{ .Values.uiPort }}
      targetPort: http-ui
      protocol: TCP
      name: http-ui
  selector:
    {{- include "agentgateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
