{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "agentregistry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentregistry.labels" . | nindent 4 }}
spec:
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.httpRoute.gatewayName }}
      {{- if .Values.httpRoute.gatewayNamespace }}
      namespace: {{ .Values.httpRoute.gatewayNamespace }}
      {{- end }}
      sectionName: {{ .Values.httpRoute.sectionName }}
  rules:
    - backendRefs:
        - name: {{ include "agentregistry.fullname" . }}-api
          port: {{ .Values.httpApi.port }}
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
